# src/baselines/sb3_ppo.py
# ============================================================================
# PPO -- Proximal Policy Optimization (Schulman et al., arXiv:1707.06347, 2017)
#
# Basic baseline 1/3, implemented via Stable-Baselines3 (`stable_baselines3.PPO`)
# and wrapped for our hybrid grant with the shared 3-dim Box wrapper in
# `src/baselines/sb3_wrapper.py` (dims 0,1 -> Delta, p; dim 2 binned to one of
# the num_channels subchannels). The wrapper is deliberately identical for
# PPO/SAC/TD3 so the three basic baselines stay comparable, per
# librarian/baselines_v2.json.
#
# ALTERNATIVE IF THE BINNING PROVES LOSSY (recorded per the spec): replace the
# flat Box with a `MultiInputPolicy` carrying a custom distribution that
# combines a DiagGaussian over (Delta, p) with a Categorical over ch. That
# recovers an exact discrete head and a proper per-channel log-probability, at
# the cost of a hand-written `Distribution` subclass and of no longer sharing
# the wrapper with SAC/TD3 (both of which are Box-only in SB3). Diagnostic that
# would trigger the switch: the learned marginal over dim 2 collapsing onto one
# bin, or the |dim-2| entropy staying pinned while Delta/p entropy falls.
#
# ---------------------------------------------------------------------------
# ON-POLICY / OFF-POLICY MISMATCH -- what remains of it after the 2026-09-04 fix.
#
# PPO is on-policy. Our pipeline is off-policy in shape: `hot_swap_trainer`
# streams retrospective SMDP transitions into `RetrospectiveReplayBuffer` and
# calls `update(batch)` with a uniformly sampled minibatch, where the behaviour
# policy is a *stale* Act model (weights as of the last hot-swap, up to
# `swap_interval` gradient steps old) and the transitions in one batch were not
# even generated by the same policy as each other.
#
# The bridge implemented below treats each sampled batch as one short rollout:
#
#   * The bootstrap target is a 1-step SMDP TD target,
#         return = r + (1 - done) * gamma**delta_t * V(s'),
#     i.e. GAE with lambda = 0. Multi-step GAE is not available because the
#     buffer stores independent transitions, not contiguous trajectories.
#   * `old_log_prob` is the BEHAVIOUR log-probability the acting policy reported
#     at selection time and the buffer stored alongside the transition
#     (`batch["behaviour_log_prob"]`), so the surrogate carries the true
#     importance weight pi_new / pi_behaviour and the clip range binds against
#     the policy that actually collected the data.
#
# WHAT THIS REPLACED, AND WHY IT MATTERED. `old_log_prob` used to be recomputed
# from the *current* policy under no_grad at the top of `update()`. That makes
# the ratio exactly 1 on the first inner epoch, and PPO's clipping only acts when
# the ratio leaves [1-eps, 1+eps], so the first epoch was an UNCLIPPED policy
# gradient step on stale data and the trust region bound only between the start
# and the end of one `update()` call. Both on-policy baselines diverged from it:
# PPO went NaN at env step 588 with the tuned learning rate AND at 2,493 with the
# textbook 3e-4 (`results/hpo/divergence_detection_check.csv`), which is why the
# learning rate was never the cause.
#
# THE FALLBACK IS STILL HERE and still carries the old caveat, because callers
# exist that do not supply the key (hand-built batches, older checkpointed
# buffers). It is not silent: `update()` returns `behaviour_logp_stored = 0.0`
# and logs a warning the first time, since in that mode the ratio is identically
# 1 on the first epoch and the clipping is inert.
# ============================================================================

from __future__ import annotations

from typing import Any, Dict, List, Optional, Tuple, Union

import numpy as np
import torch
import torch.nn.functional as F
from stable_baselines3 import PPO as SB3PPO

from src.baselines.base_agent import LOG_RATIO_CLAMP
from src.baselines.sb3_wrapper import SB3BaselineModel
from src.rl_interface import STATE_DIM


class PPO(SB3BaselineModel):
    """PPO baseline backed by `stable_baselines3.PPO`'s ActorCriticPolicy."""

    SB3_ALGO = SB3PPO

    def __init__(
        self,
        state_dim: int = STATE_DIM,
        num_channels: int = 4,
        learning_rate: float = 3e-4,
        n_epochs: int = 10,
        gamma: float = 0.99,
        clip_range: float = 0.2,
        clip_range_vf: Optional[float] = None,
        ent_coef: float = 0.0,
        vf_coef: float = 0.5,
        max_grad_norm: float = 0.5,
        normalize_advantage: bool = True,
        target_kl: Optional[float] = None,
        policy: str = "MlpPolicy",
        policy_kwargs: Optional[Dict[str, Any]] = None,
        hidden_dim: Optional[int] = None,
        device: Union[str, torch.device] = "auto",
        seed: Optional[int] = None,
        rollout_n_steps: int = 64,
        **hparams: Any,
    ) -> None:
        super().__init__(state_dim=state_dim, num_channels=num_channels, **hparams)
        self.gamma = float(gamma)
        #: Requested hidden width; None means "keep SB3's own default net_arch".
        self.hidden_dim = None if hidden_dim is None else int(hidden_dim)

        # `rollout_n_steps` only sizes SB3's internal RolloutBuffer, which we never
        # fill (our data comes from RetrospectiveReplayBuffer). It is kept small so
        # two models -- Act and Rest -- do not allocate a 2048-step buffer each.
        self._build_sb3(
            SB3PPO,
            policy=policy,
            device=device,
            seed=seed,
            learning_rate=learning_rate,
            n_steps=int(rollout_n_steps),
            batch_size=int(rollout_n_steps),
            n_epochs=int(n_epochs),
            gamma=self.gamma,
            clip_range=clip_range,
            clip_range_vf=clip_range_vf,
            ent_coef=ent_coef,
            vf_coef=vf_coef,
            max_grad_norm=max_grad_norm,
            normalize_advantage=bool(normalize_advantage),
            target_kl=target_kl,
            policy_kwargs=self.apply_hidden_dim(policy_kwargs, hidden_dim),
        )

    # ------------------------------------------------------------------
    def sb3_optimizers(self) -> List[torch.optim.Optimizer]:
        return [self.policy.optimizer]

    # ------------------------------------------------------------------
    def select_action(
        self,
        state: Union[np.ndarray, torch.Tensor],
        deterministic: bool = False,
    ) -> Tuple[Tuple[float, int, float], np.ndarray, Dict[str, Any]]:
        """
        Sample a grant from the Gaussian actor and decode it through the wrapper.

        The RAW (unclipped) Box vector is returned, because that is what gets
        stored in the replay buffer and what `evaluate_actions` must later be
        given for the log-probability to be the one that was actually realized.
        Clipping happens only inside the wrapper, when decoding to a grant.
        """
        obs = self._prepare_state_tensor(state)
        was_training = self.policy.training
        self.policy.set_training_mode(False)
        with torch.no_grad():
            actions, values, log_prob = self.policy(obs, deterministic=deterministic)
        self.policy.set_training_mode(was_training)

        raw_action = actions.detach().cpu().numpy().reshape(-1).astype(np.float32)
        grant = self.decode(raw_action)
        info: Dict[str, Any] = {
            "value": float(values.detach().cpu().reshape(-1)[0]),
            "log_prob": float(log_prob.detach().cpu().reshape(-1)[0]),
            "delta_s": grant[0],
            "channel_idx": grant[1],
            "power_dbm": grant[2],
        }
        return grant, raw_action, info

    # ------------------------------------------------------------------
    def behaviour_log_prob(
        self,
        batch: Dict[str, torch.Tensor],
        states: torch.Tensor,
        actions: torch.Tensor,
    ) -> Tuple[torch.Tensor, bool]:
        """Denominator of the importance ratio, and whether it is the real one.

        Preferred path: the log-probability the ACTING policy reported when it
        emitted this action, carried through the streamer and the replay buffer
        (`BaseRLModel.stored_behaviour_log_prob`). Fallback, for batches built by
        hand or restored from a buffer written before the column existed: the
        current policy re-evaluated on the same (s, a), which is what this method
        replaced and which makes the first-epoch ratio identically 1.
        """
        reference = torch.zeros(states.shape[0], 1, dtype=states.dtype, device=states.device)
        stored = self.stored_behaviour_log_prob(batch, reference)
        if stored is not None:
            return stored.detach(), True
        _, recomputed, _ = self.policy.evaluate_actions(states, actions)
        return recomputed.detach().reshape(-1, 1), False

    # ------------------------------------------------------------------
    def update(self, batch: Dict[str, torch.Tensor]) -> Dict[str, float]:
        """
        One PPO update treating the sampled batch as a single short rollout.

        See the module header for the on-policy/off-policy caveat this carries.
        Mirrors `stable_baselines3.PPO.train()` except that the advantage comes
        from a 1-step SMDP TD target instead of GAE over a contiguous rollout.
        `old_log_prob` is the stored behaviour log-probability when the batch
        carries one, and only then does the reported `behaviour_logp_stored`
        equal 1.0.
        """
        states, actions, rewards, next_states, dones, discounts = self.unpack_batch(batch)
        sb3 = self._sb3
        self.policy.set_training_mode(True)

        # SB3 stores clip_range/clip_range_vf as schedules over the remaining
        # progress; our loop has no global progress signal, so evaluate at 1.0
        # (the constant-schedule case returns the configured value).
        clip_range = float(sb3.clip_range(1.0))
        clip_range_vf = float(sb3.clip_range_vf(1.0)) if sb3.clip_range_vf is not None else None

        with torch.no_grad():
            old_values = self.policy.predict_values(states).reshape(-1, 1)
            next_values = self.policy.predict_values(next_states).reshape(-1, 1)
            # lambda = 0 GAE: the buffer holds independent SMDP transitions, so a
            # multi-step advantage cannot be formed. gamma**delta_t comes per-sample.
            returns = rewards + (1.0 - dones) * discounts * next_values
            advantages = returns - old_values
            old_log_prob, behaviour_stored = self.behaviour_log_prob(batch, states, actions)

        n_epochs = int(sb3.n_epochs)
        pg_losses: List[float] = []
        value_losses: List[float] = []
        entropy_losses: List[float] = []
        clip_fractions: List[float] = []
        approx_kls: List[float] = []
        total_loss_val = 0.0
        epochs_run = 0
        first_ratio_mean = 1.0
        first_ratio_std = 0.0
        first_ratio_max = 1.0
        first_clip_fraction = 0.0

        for _ in range(n_epochs):
            values, log_prob, entropy = self.policy.evaluate_actions(states, actions)
            values = values.reshape(-1, 1)

            adv = advantages
            if sb3.normalize_advantage and adv.shape[0] > 1:
                adv = (adv - adv.mean()) / (adv.std() + 1e-8)

            # The log-ratio is clamped before exponentiation. With a genuine
            # behaviour policy the ratio is no longer pinned at 1, and a
            # transition the current policy has moved far away from can produce
            # exp() of a few hundred, i.e. inf in float32 -- the clamp bounds the
            # surrogate at exp(+-20) instead. Outside the clamp the gradient is
            # zero, which is the intended trust-region behaviour and is what
            # `i_hamappo` already does.
            log_ratio = torch.clamp(
                log_prob.reshape(-1, 1) - old_log_prob.reshape(-1, 1),
                -LOG_RATIO_CLAMP,
                LOG_RATIO_CLAMP,
            )
            ratio = torch.exp(log_ratio)
            policy_loss_1 = adv * ratio
            policy_loss_2 = adv * torch.clamp(ratio, 1.0 - clip_range, 1.0 + clip_range)
            policy_loss = -torch.min(policy_loss_1, policy_loss_2).mean()

            if clip_range_vf is None:
                values_pred = values
            else:
                values_pred = old_values + torch.clamp(values - old_values, -clip_range_vf, clip_range_vf)
            value_loss = F.mse_loss(returns, values_pred)

            if entropy is None:
                entropy_loss = -torch.mean(-log_prob)
            else:
                entropy_loss = -torch.mean(entropy)

            loss = policy_loss + sb3.ent_coef * entropy_loss + sb3.vf_coef * value_loss

            with torch.no_grad():
                approx_kl = torch.mean((ratio - 1.0) - log_ratio).item()
                clip_fraction = torch.mean((torch.abs(ratio - 1.0) > clip_range).float()).item()
                if epochs_run == 0:
                    # First-epoch ratio statistics. This is the number that
                    # diagnoses the bug this module used to have: with a
                    # recomputed `old_log_prob` it is exactly 1.0 with zero
                    # spread and a clip fraction of 0, so the first and largest
                    # gradient step of every update was unclipped.
                    first_ratio_mean = float(ratio.mean().item())
                    first_ratio_std = float(ratio.std().item()) if ratio.numel() > 1 else 0.0
                    first_ratio_max = float(ratio.max().item())
                    first_clip_fraction = float(clip_fraction)

            pg_losses.append(policy_loss.item())
            value_losses.append(value_loss.item())
            entropy_losses.append(entropy_loss.item())
            clip_fractions.append(clip_fraction)
            approx_kls.append(approx_kl)
            total_loss_val = loss.item()

            self.policy.optimizer.zero_grad()
            loss.backward()
            torch.nn.utils.clip_grad_norm_(self.policy.parameters(), sb3.max_grad_norm)
            self.policy.optimizer.step()
            epochs_run += 1

            # SB3's KL early stop. `approx_kl` is now measured against the
            # behaviour policy, so it starts non-zero at the first epoch and this
            # stop can fire immediately -- which is the correct reading of a
            # batch the current policy has already moved far away from.
            if sb3.target_kl is not None and approx_kl > 1.5 * float(sb3.target_kl):
                break

        sb3._n_updates += epochs_run
        return {
            "loss": float(total_loss_val),
            "policy_loss": float(np.mean(pg_losses)),
            "value_loss": float(np.mean(value_losses)),
            "entropy_loss": float(np.mean(entropy_losses)),
            "approx_kl": float(np.mean(approx_kls)),
            "clip_fraction": float(np.mean(clip_fractions)),
            "epochs": float(epochs_run),
            # 1.0 only when the true behaviour log-prob was available. At 0.0 the
            # first-epoch ratio is identically 1 and the clipping does nothing --
            # the caveat in the module header applies to that update.
            "behaviour_logp_stored": 1.0 if behaviour_stored else 0.0,
            "first_epoch_ratio_mean": first_ratio_mean,
            "first_epoch_ratio_std": first_ratio_std,
            "first_epoch_ratio_max": first_ratio_max,
            "first_epoch_clip_fraction": first_clip_fraction,
        }
