#!/usr/bin/env python3
"""
test_c1_c2_wiring.py
====================
Independent verification test suite for C-1 and C-2:
1. C-1: DRL 5-model registration in sensitivity_runner sweeps & removal of Proposed (TinyMLP).
2. C-2: setup_eval_hook wiring, checkpoint weight loading, agent injection, eval mode (epsilon=0, is_training=False).
3. Action Diversity: Verifies that trained neural network models output diverse, non-trivial actions
   rather than the fallback action (0) during multi-step simulation.

Author: Paper4 Coder Worker (worker_c1_c2)
"""

import os
import sys
import unittest
import numpy as np
from collections import Counter

# Set path to code/
_code_dir = os.path.dirname(os.path.abspath(__file__))
if _code_dir not in sys.path:
    sys.path.insert(0, _code_dir)

from sensitivity_runner import define_sweeps, setup_eval_hook, DRL_SETUP
from sim_engine import SimulationRunner
from ai_dcc_hook import get_hook


class TestC1C2Wiring(unittest.TestCase):
    def setUp(self):
        self.drl_models = ["VanillaDQN", "DoubleDQN", "DuelingDQN", "MoEDQN", "ResNetMoEDQN"]

    def test_01_c1_sweeps_registration_and_proposed_removal(self):
        """Verify SA1 and SA2 have all 5 DRL models registered and 'Proposed' completely removed."""
        sweeps = define_sweeps()
        self.assertIn("SA1", sweeps)
        self.assertIn("SA2", sweeps)

        # Inspect SA1 methods
        sa1_methods = {r["runner_kwargs"]["method"] for r in sweeps["SA1"]}
        print(f"\n[Test 1] SA1 registered methods ({len(sa1_methods)}): {sorted(sa1_methods)}")
        for m in self.drl_models:
            self.assertIn(m, sa1_methods, f"DRL model {m} must be in SA1 sweep")
        self.assertNotIn("Proposed", sa1_methods, "'Proposed' must NOT be in SA1 sweep")

        # Inspect SA2 methods
        sa2_methods = {r["runner_kwargs"]["method"] for r in sweeps["SA2"]}
        print(f"[Test 1] SA2 registered methods ({len(sa2_methods)}): {sorted(sa2_methods)}")
        for m in self.drl_models:
            self.assertIn(m, sa2_methods, f"DRL model {m} must be in SA2 sweep")
        self.assertNotIn("Proposed", sa2_methods, "'Proposed' must NOT be in SA2 sweep")

    def test_02_c2_setup_eval_hook_loading_and_integrity(self):
        """Verify setup_eval_hook correctly initializes, loads weights, and sets eval flags for all 5 DRL models."""
        print("\n[Test 2] Testing setup_eval_hook for each DRL model:")
        for method in self.drl_models:
            hook = setup_eval_hook(method)
            self.assertIsNotNone(hook, f"setup_eval_hook({method}) returned None")
            self.assertIsNotNone(hook.agent, f"Hook for {method} must have agent injected")
            self.assertFalse(hook.is_training, f"Hook for {method} must have is_training == False")

            # Check agent evaluation properties
            if hasattr(hook.agent, "epsilon"):
                self.assertEqual(hook.agent.epsilon, 0.0, f"Agent epsilon for {method} must be 0.0")

            # Verify agent can make valid predictions on synthetic states
            sample_state = np.array([0.05, 0.4, 0.5, 0.2, 0.045], dtype=np.float32)
            act_idx = hook.agent.act(sample_state, evaluate=True)
            self.assertIsInstance(act_idx, (int, np.integer))
            self.assertGreaterEqual(act_idx, 0)
            self.assertLess(act_idx, 24)  # within valid action range
            print(f"  ✓ {method:12s}: Agent loaded, eval mode confirmed, sample action={act_idx}")

    def test_03_simulation_execution_and_action_diversity(self):
        """
        Run a 300-step simulation for each of the 5 DRL models.
        Collect all predicted actions and assert:
        1. Simulation completes with status 'ok' and valid metrics (AoI, CBR, PDR).
        2. Predictions are generated by the neural network (agent != None).
        3. Actions exhibit diversity across the simulation and are NOT stuck at fallback action 0.
        """
        print("\n[Test 3] Running 300-step simulation & action diversity analysis for 5 DRL models:")
        
        for method in self.drl_models:
            hook = setup_eval_hook(method)
            self.assertIsNotNone(hook.agent, f"Agent not set for {method}")

            # Intercept hook.predict to record generated actions
            recorded_actions = []
            original_predict = hook.predict

            def tracked_predict(*args, **kwargs):
                # State: cbr_global, n_neighbors, v_norm, dt_since_last_cam, cbr_smoothed
                cbr_g = args[0] if len(args) > 0 else kwargs.get("cbr_global", 0.0)
                n_n = args[1] if len(args) > 1 else kwargs.get("n_neighbors", 0.0)
                v_n = args[2] if len(args) > 2 else kwargs.get("v_norm", 0.0)
                dt_c = args[3] if len(args) > 3 else kwargs.get("dt_since_last_cam", 0.0)
                cbr_s = args[4] if len(args) > 4 else kwargs.get("cbr_smoothed", 0.0)
                state = np.array([cbr_g, n_n, v_n, dt_c, cbr_s], dtype=np.float32)
                
                # Check agent act
                if hook.agent is not None:
                    act_idx = hook.agent.act(state, evaluate=not hook.is_training)
                else:
                    act_idx = 0
                recorded_actions.append(act_idx)
                return original_predict(*args, **kwargs)

            hook.predict = tracked_predict

            try:
                runner = SimulationRunner(
                    scenario="urban_grid",
                    n_vehicles=30,
                    seed=42,
                    method=method,
                    method_params={},
                    duration_steps=300,
                    warmup_s=5.0
                )
                metrics = runner.run()
            finally:
                # Restore original predict
                hook.predict = original_predict

            # Verification 1: Simulation metrics sanity
            self.assertIsNotNone(metrics.get("AoI_mean"), f"{method} AoI_mean is None")
            self.assertIsNotNone(metrics.get("CBR_mean"), f"{method} CBR_mean is None")
            self.assertIsNotNone(metrics.get("PDR_mean"), f"{method} PDR_mean is None")
            
            # Verification 2: Action count & diversity
            total_actions = len(recorded_actions)
            self.assertGreater(total_actions, 100, f"Expected >100 action decisions, got {total_actions}")
            
            action_counts = Counter(recorded_actions)
            unique_actions = len(action_counts)
            
            print(f"\n  ▶ Model: {method:12s} | Steps: 300 | Decisions: {total_actions}")
            print(f"    Metrics: AoI={metrics['AoI_mean']:.3f}s | CBR={metrics['CBR_mean']:.4f} | PDR={metrics['PDR_mean']:.3f}")
            print(f"    Action Distribution (Unique={unique_actions}):")
            for act, cnt in sorted(action_counts.items()):
                pct = (cnt / total_actions) * 100.0
                n_p = len(hook.p_tx_grid)
                t_val = hook.t_grid[act // n_p]
                p_val = hook.p_tx_grid[act % n_p]
                print(f"      Action {act:2d} (T={t_val:.1f}s, P={p_val:4.1f}dBm): {cnt:4d} times ({pct:5.1f}%)")

            # Core Assertion: Action is NOT 100% fixed to fallback 0
            fallback_ratio = action_counts.get(0, 0) / total_actions
            self.assertLess(
                fallback_ratio, 1.0, 
                f"Model {method} output was 100% stuck at fallback action 0! Model weights not actively driving decisions."
            )
            # Ensure neural network produced multiple diverse actions under varying channel conditions
            self.assertGreaterEqual(
                unique_actions, 2,
                f"Model {method} should output at least 2 distinct actions across diverse network conditions."
            )

    def test_04_eval_mode_memory_and_exploration_invariance(self):
        """Verify that evaluation does not pollute replay buffer and maintains deterministic exploitation."""
        for method in self.drl_models:
            hook = setup_eval_hook(method)
            initial_mem_len = len(hook.agent.memory) if hasattr(hook.agent, "memory") else 0
            
            # Predict multiple times with vid attached
            for step in range(50):
                cbr_val = 0.02 + 0.001 * (step % 20)
                hook.predict(
                    cbr_global=cbr_val,
                    n_neighbors=0.5,
                    v_norm=0.4,
                    dt_since_last_cam=0.1 * (step % 5 + 1),
                    cbr_smoothed=cbr_val,
                    vid="veh_eval_test"
                )

            # Assert replay buffer was not mutated
            if hasattr(hook.agent, "memory"):
                self.assertEqual(
                    len(hook.agent.memory), initial_mem_len,
                    f"Replay buffer mutated during evaluation for {method}!"
                )
            self.assertEqual(hook.agent.epsilon, 0.0, f"Agent epsilon mutated for {method}")
        print("\n[Test 4] ✓ Eval mode memory invariance & exploration freeze verified for all 5 models.")


if __name__ == "__main__":
    unittest.main()
