# src/baselines/sb3_ppo.py
# ============================================================================
# PPO -- Proximal Policy Optimization (Schulman et al., arXiv:1707.06347, 2017)
#
# Basic baseline 1/3, implemented via Stable-Baselines3 (`stable_baselines3.PPO`)
# and wrapped for our hybrid grant with the shared 3-dim Box wrapper in
# `src/baselines/sb3_wrapper.py` (dims 0,1 -> Delta, p; dim 2 binned to one of
# the num_channels subchannels). The wrapper is deliberately identical for
# PPO/SAC/TD3 so the three basic baselines stay comparable, per
# librarian/baselines_v2.json.
#
# ALTERNATIVE IF THE BINNING PROVES LOSSY (recorded per the spec): replace the
# flat Box with a `MultiInputPolicy` carrying a custom distribution that
# combines a DiagGaussian over (Delta, p) with a Categorical over ch. That
# recovers an exact discrete head and a proper per-channel log-probability, at
# the cost of a hand-written `Distribution` subclass and of no longer sharing
# the wrapper with SAC/TD3 (both of which are Box-only in SB3). Diagnostic that
# would trigger the switch: the learned marginal over dim 2 collapsing onto one
# bin, or the |dim-2| entropy staying pinned while Delta/p entropy falls.
#
# ---------------------------------------------------------------------------
# ON-POLICY / OFF-POLICY MISMATCH -- stated honestly, not papered over.
#
# PPO is on-policy. Our pipeline is off-policy in shape: `hot_swap_trainer`
# streams retrospective SMDP transitions into `RetrospectiveReplayBuffer` and
# calls `update(batch)` with a uniformly sampled minibatch, where the behaviour
# policy is a *stale* Act model (weights as of the last hot-swap, up to
# `swap_interval` gradient steps old) and the transitions in one batch were not
# even generated by the same policy as each other.
#
# The bridge implemented below treats each sampled batch as one short rollout:
#
#   * The bootstrap target is a 1-step SMDP TD target,
#         return = r + (1 - done) * gamma**delta_t * V(s'),
#     i.e. GAE with lambda = 0. Multi-step GAE is not available because the
#     buffer stores independent transitions, not contiguous trajectories.
#   * `old_log_prob` is recomputed from the *current* policy under no_grad at
#     the top of `update()`, so the first inner epoch has ratio == 1 exactly and
#     the following `n_epochs - 1` epochs get a genuine clipped surrogate.
#
# THE RESULTING CAVEAT: the PPO trust region is therefore enforced only between
# the start and the end of a single `update()` call -- NOT between the behaviour
# policy that actually collected the data and the updated policy. The true
# importance weight pi_new/pi_behaviour is unavailable (the buffer does not store
# the behaviour log-prob), so the off-policy correction PPO relies on is simply
# absent. What is left is a clipped, entropy-regularized, advantage-weighted
# policy-gradient step on stale data. This is a real approximation and it is the
# expected reason PPO underperforms the off-policy baselines here; it must be
# reported as such in the paper rather than presented as textbook PPO.
#
# (Making it exact would require storing the behaviour log-prob alongside each
# transition -- a change to `RetrospectiveReplayBuffer.push`, which is outside
# this module's ownership.)
# ============================================================================

from __future__ import annotations

from typing import Any, Dict, List, Optional, Tuple, Union

import numpy as np
import torch
import torch.nn.functional as F
from stable_baselines3 import PPO as SB3PPO

from src.baselines.sb3_wrapper import SB3BaselineModel
from src.rl_interface import STATE_DIM


class PPO(SB3BaselineModel):
    """PPO baseline backed by `stable_baselines3.PPO`'s ActorCriticPolicy."""

    SB3_ALGO = SB3PPO

    def __init__(
        self,
        state_dim: int = STATE_DIM,
        num_channels: int = 4,
        learning_rate: float = 3e-4,
        n_epochs: int = 10,
        gamma: float = 0.99,
        clip_range: float = 0.2,
        clip_range_vf: Optional[float] = None,
        ent_coef: float = 0.0,
        vf_coef: float = 0.5,
        max_grad_norm: float = 0.5,
        normalize_advantage: bool = True,
        target_kl: Optional[float] = None,
        policy: str = "MlpPolicy",
        policy_kwargs: Optional[Dict[str, Any]] = None,
        device: Union[str, torch.device] = "auto",
        seed: Optional[int] = None,
        rollout_n_steps: int = 64,
        **hparams: Any,
    ) -> None:
        super().__init__(state_dim=state_dim, num_channels=num_channels, **hparams)
        self.gamma = float(gamma)

        # `rollout_n_steps` only sizes SB3's internal RolloutBuffer, which we never
        # fill (our data comes from RetrospectiveReplayBuffer). It is kept small so
        # two models -- Act and Rest -- do not allocate a 2048-step buffer each.
        self._build_sb3(
            SB3PPO,
            policy=policy,
            device=device,
            seed=seed,
            learning_rate=learning_rate,
            n_steps=int(rollout_n_steps),
            batch_size=int(rollout_n_steps),
            n_epochs=int(n_epochs),
            gamma=self.gamma,
            clip_range=clip_range,
            clip_range_vf=clip_range_vf,
            ent_coef=ent_coef,
            vf_coef=vf_coef,
            max_grad_norm=max_grad_norm,
            normalize_advantage=bool(normalize_advantage),
            target_kl=target_kl,
            policy_kwargs=policy_kwargs,
        )

    # ------------------------------------------------------------------
    def sb3_optimizers(self) -> List[torch.optim.Optimizer]:
        return [self.policy.optimizer]

    # ------------------------------------------------------------------
    def select_action(
        self,
        state: Union[np.ndarray, torch.Tensor],
        deterministic: bool = False,
    ) -> Tuple[Tuple[float, int, float], np.ndarray, Dict[str, Any]]:
        """
        Sample a grant from the Gaussian actor and decode it through the wrapper.

        The RAW (unclipped) Box vector is returned, because that is what gets
        stored in the replay buffer and what `evaluate_actions` must later be
        given for the log-probability to be the one that was actually realized.
        Clipping happens only inside the wrapper, when decoding to a grant.
        """
        obs = self._prepare_state_tensor(state)
        was_training = self.policy.training
        self.policy.set_training_mode(False)
        with torch.no_grad():
            actions, values, log_prob = self.policy(obs, deterministic=deterministic)
        self.policy.set_training_mode(was_training)

        raw_action = actions.detach().cpu().numpy().reshape(-1).astype(np.float32)
        grant = self.decode(raw_action)
        info: Dict[str, Any] = {
            "value": float(values.detach().cpu().reshape(-1)[0]),
            "log_prob": float(log_prob.detach().cpu().reshape(-1)[0]),
            "delta_s": grant[0],
            "channel_idx": grant[1],
            "power_dbm": grant[2],
        }
        return grant, raw_action, info

    # ------------------------------------------------------------------
    def update(self, batch: Dict[str, torch.Tensor]) -> Dict[str, float]:
        """
        One PPO update treating the sampled batch as a single short rollout.

        See the module header for the on-policy/off-policy caveat this carries.
        Mirrors `stable_baselines3.PPO.train()` except that (a) the advantage
        comes from a 1-step SMDP TD target instead of GAE over a contiguous
        rollout, and (b) `old_log_prob` is a snapshot of the current policy
        rather than the true behaviour policy.
        """
        states, actions, rewards, next_states, dones, discounts = self.unpack_batch(batch)
        sb3 = self._sb3
        self.policy.set_training_mode(True)

        # SB3 stores clip_range/clip_range_vf as schedules over the remaining
        # progress; our loop has no global progress signal, so evaluate at 1.0
        # (the constant-schedule case returns the configured value).
        clip_range = float(sb3.clip_range(1.0))
        clip_range_vf = float(sb3.clip_range_vf(1.0)) if sb3.clip_range_vf is not None else None

        with torch.no_grad():
            old_values = self.policy.predict_values(states).reshape(-1, 1)
            next_values = self.policy.predict_values(next_states).reshape(-1, 1)
            # lambda = 0 GAE: the buffer holds independent SMDP transitions, so a
            # multi-step advantage cannot be formed. gamma**delta_t comes per-sample.
            returns = rewards + (1.0 - dones) * discounts * next_values
            advantages = returns - old_values
            _, old_log_prob, _ = self.policy.evaluate_actions(states, actions)
            old_log_prob = old_log_prob.detach()

        n_epochs = int(sb3.n_epochs)
        pg_losses: List[float] = []
        value_losses: List[float] = []
        entropy_losses: List[float] = []
        clip_fractions: List[float] = []
        approx_kls: List[float] = []
        total_loss_val = 0.0
        epochs_run = 0

        for _ in range(n_epochs):
            values, log_prob, entropy = self.policy.evaluate_actions(states, actions)
            values = values.reshape(-1, 1)

            adv = advantages
            if sb3.normalize_advantage and adv.shape[0] > 1:
                adv = (adv - adv.mean()) / (adv.std() + 1e-8)

            ratio = torch.exp(log_prob.reshape(-1, 1) - old_log_prob.reshape(-1, 1))
            policy_loss_1 = adv * ratio
            policy_loss_2 = adv * torch.clamp(ratio, 1.0 - clip_range, 1.0 + clip_range)
            policy_loss = -torch.min(policy_loss_1, policy_loss_2).mean()

            if clip_range_vf is None:
                values_pred = values
            else:
                values_pred = old_values + torch.clamp(values - old_values, -clip_range_vf, clip_range_vf)
            value_loss = F.mse_loss(returns, values_pred)

            if entropy is None:
                entropy_loss = -torch.mean(-log_prob)
            else:
                entropy_loss = -torch.mean(entropy)

            loss = policy_loss + sb3.ent_coef * entropy_loss + sb3.vf_coef * value_loss

            with torch.no_grad():
                log_ratio = log_prob.reshape(-1, 1) - old_log_prob.reshape(-1, 1)
                approx_kl = torch.mean((torch.exp(log_ratio) - 1.0) - log_ratio).item()
                clip_fraction = torch.mean((torch.abs(ratio - 1.0) > clip_range).float()).item()

            pg_losses.append(policy_loss.item())
            value_losses.append(value_loss.item())
            entropy_losses.append(entropy_loss.item())
            clip_fractions.append(clip_fraction)
            approx_kls.append(approx_kl)
            total_loss_val = loss.item()

            self.policy.optimizer.zero_grad()
            loss.backward()
            torch.nn.utils.clip_grad_norm_(self.policy.parameters(), sb3.max_grad_norm)
            self.policy.optimizer.step()
            epochs_run += 1

            # SB3's KL early stop, kept so the trust region at least binds within
            # the update even though it cannot bind against the behaviour policy.
            if sb3.target_kl is not None and approx_kl > 1.5 * float(sb3.target_kl):
                break

        sb3._n_updates += epochs_run
        return {
            "loss": float(total_loss_val),
            "policy_loss": float(np.mean(pg_losses)),
            "value_loss": float(np.mean(value_losses)),
            "entropy_loss": float(np.mean(entropy_losses)),
            "approx_kl": float(np.mean(approx_kls)),
            "clip_fraction": float(np.mean(clip_fractions)),
            "epochs": float(epochs_run),
        }
